baseURL = "https://thomasswtco.github.io/coole-teile/"
title = "Spectral"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Wszystkiego najlepszego z okazji urodzin <br/> la Binczycka <br/> ğŸ‚âœ¨ğŸ„" # title for frontpage, may include image
# copyright = "John Doe"
description = 'Le site est en ligne, maintenant go chercher les champignons'
startbuttonText = "Check Coole Teile"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]


